# 🚀 Day 4: Pandas for Machine Learning

## 30 Days of Machine Learning Challenge

Today I am learning Pandas, one of the most important Python libraries for Data Science and Machine Learning.

### Objectives

- Understand Pandas
- Create Series and DataFrames
- Load and explore data
- Select columns and rows
- Filter data
- Sort data
- Handle missing values
- Use groupby()
- Calculate basic statistics
- Understand Pandas in Machine Learning

## 📚 What is Pandas?

Pandas is a Python library used for:

- Data manipulation
- Data cleaning
- Data analysis
- Working with structured/tabular data

The two main Pandas structures are:

1. Series
2. DataFrame

In [1]:
import pandas as pd

print("Pandas Version:", pd.__version__)

Pandas Version: 2.2.2

In [2]:
marks = pd.Series([70, 80, 90, 85, 95])

print(marks)

0    70
1    80
2    90
3    85
4    95
dtype: int64

In [3]:
data = {
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Neha"],
    "Age": [22, 21, 23, 22, 24],
    "City": ["Pune", "Mumbai", "Pune", "Nashik", "Mumbai"],
    "Marks": [85, 90, 78, 88, 95]
}

df = pd.DataFrame(data)

df

    Name  Age    City  Marks
0   Amit   22    Pune     85
1  Priya   21  Mumbai     90
2  Rahul   23    Pune     78
3  Sneha   22  Nashik     88
4   Neha   24  Mumbai     95

In [4]:
print(df.head())

    Name  Age    City  Marks
0   Amit   22    Pune     85
1  Priya   21  Mumbai     90
2  Rahul   23    Pune     78
3  Sneha   22  Nashik     88
4   Neha   24  Mumbai     95

In [5]:
print(df.tail())

    Name  Age    City  Marks
0   Amit   22    Pune     85
1  Priya   21  Mumbai     90
2  Rahul   23    Pune     78
3  Sneha   22  Nashik     88
4   Neha   24  Mumbai     95

In [6]:
print("Shape:", df.shape)

Shape: (5, 4)

In [7]:
print("Columns:")
print(df.columns)

Columns:
Index(['Name', 'Age', 'City', 'Marks'], dtype='object')

In [8]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
 3   Marks   5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

             Age      Marks
count   5.000000   5.000000
mean   22.400000  87.200000
std     1.140175   6.300794
min    21.000000  78.000000
25%    22.000000  85.000000
50%    22.000000  88.000000
75%    23.000000  90.000000
max    24.000000  95.000000

In [9]:
print(df["Marks"])
print(df[["Name", "Marks"]])

0    85
1    90
2    78
3    88
4    95
Name: Marks, dtype: int64
    Name  Marks
0   Amit     85
1  Priya     90
2  Rahul     78
3  Sneha     88
4   Neha     95

In [10]:
print(df.iloc[0:3])

    Name  Age    City  Marks
0   Amit   22    Pune     85
1  Priya   21  Mumbai     90
2  Rahul   23    Pune     78

In [11]:
high_marks = df[df["Marks"] > 80]

print(high_marks)

    Name  Age    City  Marks
0   Amit   22    Pune     85
1  Priya   21  Mumbai     90
3  Sneha   22  Nashik     88
4   Neha   24  Mumbai     95

In [12]:
pune_students = df[df["City"] == "Pune"]

print(pune_students)

    Name  Age  City  Marks
0   Amit   22  Pune     85
2  Rahul   23  Pune     78

In [13]:
result = df[
    (df["Marks"] > 80) &
    (df["Age"] > 21)
]

print(result)

    Name  Age    City  Marks
0   Amit   22    Pune     85
3  Sneha   22  Nashik     88
4   Neha   24  Mumbai     95

In [14]:
sorted_df = df.sort_values("Marks")

print(sorted_df)

sorted_df = df.sort_values("Marks", ascending=False)

print(sorted_df)

    Name  Age    City  Marks
2  Rahul   23    Pune     78
0   Amit   22    Pune     85
3  Sneha   22  Nashik     88
1  Priya   21  Mumbai     90
4   Neha   24  Mumbai     95
    Name  Age    City  Marks
4   Neha   24  Mumbai     95
1  Priya   21  Mumbai     90
3  Sneha   22  Nashik     88
0   Amit   22    Pune     85
2  Rahul   23    Pune     78

In [15]:
df_missing = df.copy()

df_missing.loc[2, "Marks"] = None

print(df_missing)

    Name  Age    City  Marks
0   Amit   22    Pune   85.0
1  Priya   21  Mumbai   90.0
2  Rahul   23    Pune    NaN
3  Sneha   22  Nashik   88.0
4   Neha   24  Mumbai   95.0

In [16]:
print(df_missing.isnull().sum())

Name     0
Age      0
City     0
Marks    1
dtype: int64

In [17]:
df_missing["Marks"] = df_missing["Marks"].fillna(
    df_missing["Marks"].mean()
)

print(df_missing)

    Name  Age    City  Marks
0   Amit   22    Pune   85.0
1  Priya   21  Mumbai   90.0
2  Rahul   23    Pune   89.5
3  Sneha   22  Nashik   88.0
4   Neha   24  Mumbai   95.0

In [18]:
city_average = df.groupby("City")["Marks"].mean()

print(city_average)

City
Mumbai    92.5
Nashik    88.0
Pune      81.5
Name: Marks, dtype: float64

In [19]:
city_count = df.groupby("City")["Name"].count()

print(city_count)

City
Mumbai    2
Nashik    1
Pune      2
Name: Name, dtype: int64

In [20]:
print("Average Marks:", df["Marks"].mean())
print("Highest Marks:", df["Marks"].max())
print("Lowest Marks:", df["Marks"].min())

Average Marks: 87.2
Highest Marks: 95
Lowest Marks: 78

In [21]:
df["Result"] = df["Marks"].apply(
    lambda x: "Pass" if x >= 40 else "Fail"
)

df

    Name  Age    City  Marks Result
0   Amit   22    Pune     85   Pass
1  Priya   21  Mumbai     90   Pass
2  Rahul   23    Pune     78   Pass
3  Sneha   22  Nashik     88   Pass
4   Neha   24  Mumbai     95   Pass

## 🤖 Why is Pandas Important in Machine Learning?

Pandas is commonly used before model training to:

- Load datasets
- Explore data
- Clean data
- Handle missing values
- Filter records
- Create features
- Analyze patterns
- Prepare data for Machine Learning

Pandas and NumPy are often used together in ML workflows.

In [22]:
students = pd.DataFrame({
    "Name": ["A", "B", "C", "D", "E"],
    "Study_Hours": [2, 4, 5, 3, 6],
    "Marks": [55, 70, 82, 65, 90]
})

print("Dataset:")
print(students)

print("\nAverage Marks:")
print(students["Marks"].mean())

print("\nStudents scoring above 70:")
print(students[students["Marks"] > 70])

print("\nHighest Marks:")
print(students["Marks"].max())

Dataset:
  Name  Study_Hours  Marks
0    A            2     55
1    B            4     70
2    C            5     82
3    D            3     65
4    E            6     90

Average Marks:
72.4

Students scoring above 70:
  Name  Study_Hours  Marks
2    C            5     82
4    E            6     90

Highest Marks:
90