# 🚀 Day 2: Data Preprocessing

## 30 Days of Machine Learning Challenge

Data preprocessing is the process of preparing raw data before using it for Machine Learning.

### Today's Goals

- Understand data preprocessing
- Identify missing values
- Handle missing values
- Remove duplicates
- Check data types
- Handle categorical data
- Separate features and target
- Prepare clean data for Machine Learning

## 📚 What is Data Preprocessing?

Real-world data is often not ready to be directly used by a Machine Learning model.

It may contain:

- Missing values
- Duplicate records
- Incorrect data types
- Categorical values
- Outliers
- Inconsistent data

Data preprocessing helps us clean and transform this data into a suitable format for Machine Learning.

In [1]:
import pandas as pd
import numpy as np

## 🗂️ Creating a Sample Dataset

For practice, we will create a small dataset containing some common data problems.

In [2]:
data = {
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Amit", "Neha"],
    "Age": [22, 21, np.nan, 23, 22, 24],
    "City": ["Pune", "Mumbai", "Pune", "Nashik", "Pune", "Mumbai"],
    "Marks": [85, 90, 78, np.nan, 85, 95]
}

df = pd.DataFrame(data)

df

    Name   Age    City  Marks
0   Amit  22.0    Pune   85.0
1  Priya  21.0  Mumbai   90.0
2  Rahul   NaN    Pune   78.0
3  Sneha  23.0  Nashik    NaN
4   Amit  22.0    Pune   85.0
5   Neha  24.0  Mumbai   95.0

In [3]:
print("Dataset Shape:", df.shape)

print("\nColumn Names:")
print(list(df.columns))

print("\nFirst 5 Records:")
print(df.head())

Dataset Shape: (6, 4)

Column Names:
['Name', 'Age', 'City', 'Marks']

First 5 Records:
    Name   Age    City  Marks
0   Amit  22.0    Pune   85.0
1  Priya  21.0  Mumbai   90.0
2  Rahul   NaN    Pune   78.0
3  Sneha  23.0  Nashik    NaN
4   Amit  22.0    Pune   85.0

In [4]:
print("\nDataset Information:")
df.info()

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     5 non-null      float64
 2   City    6 non-null      object
 3   Marks   5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

## 🔍 Checking Missing Values

Missing values are values that are not available in the dataset.

We can identify them using:

`isnull().sum()`

In [5]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Name     0
Age      1
City     0
Marks    1
dtype: int64

## 🛠️ Handling Missing Values

There are different ways to handle missing values:

- Remove rows
- Replace with mean
- Replace with median
- Replace with mode
- Use another suitable value

The method depends on the type of data.

In [6]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

df

    Name   Age    City  Marks
0   Amit  22.0    Pune   85.0
1  Priya  21.0  Mumbai   90.0
2  Rahul  22.4    Pune   78.0
3  Sneha  23.0  Nashik   86.6
4   Amit  22.0    Pune   85.0
5   Neha  24.0  Mumbai   95.0

print(df.isnull().sum())

## 🔁 Checking Duplicate Records

Duplicate records are repeated rows in a dataset.

We can identify them using:

`duplicated()`

In [7]:
print("Duplicate Records:")
print(df.duplicated())
print("Number of Duplicates:", df.duplicated().sum())

Duplicate Records:
0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool
Number of Duplicates: 1

In [8]:
df = df.drop_duplicates()

print("Shape After Removing Duplicates:", df.shape)

Shape After Removing Duplicates: (5, 4)

## 🔤 Checking Data Types

Machine Learning models require data to be in appropriate formats.

We can check column data types using:

`dtypes`

In [9]:
print(df.dtypes)

Name      object
Age      float64
City      object
Marks    float64
dtype: object

## 🏙️ Categorical Data

Categorical data contains categories or labels.

Example:

- Pune
- Mumbai
- Nashik

Machine Learning models generally work with numerical values, so categorical data may need to be converted into numerical form.

In [10]:
df_encoded = pd.get_dummies(
    df,
    columns=["City"],
    dtype=int
)

df_encoded

    Name   Age  Marks  City_Mumbai  City_Nashik  City_Pune
0   Amit  22.0   85.0            0            0          1
1  Priya  21.0   90.0            1            0          0
2  Rahul  22.4   78.0            0            0          1
3  Sneha  23.0   86.6            0            1          0
5   Neha  24.0   95.0            1            0          0

## 🎯 Features and Target

Features are the input variables used by the model.

The target is the value that we want the model to predict.

For example:

Features → Age, City

Target → Marks

In [11]:
X = df_encoded.drop("Marks", axis=1)

y = df_encoded["Marks"]

print("Features:")
print(X.head())

print("\nTarget:")
print(y.head())

Features:
    Name   Age  City_Mumbai  City_Nashik  City_Pune
0   Amit  22.0            0            0          1
1  Priya  21.0            1            0          0
2  Rahul  22.4            0            0          1
3  Sneha  23.0            0            1          0
5   Neha  24.0            1            0          0

Target:
0    85.0
1    90.0
2    78.0
3    86.6
5    95.0
Name: Marks, dtype: float64

## ✂️ Train-Test Split

We divide our dataset into two parts:

### Training Data
Used to train the Machine Learning model.

### Testing Data
Used to evaluate how well the model performs on unseen data.

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data:", X_train.shape)

print("Testing Data:", X_test.shape)

Training Data: (4, 5)
Testing Data: (1, 5)